image: mcr.microsoft.com/dotnet/sdk:6.0

definitions:
    steps:
        - step: &Restore-step
            name: Restore Solution
            script:
                - dotnet restore
        - step: &Build-step
            name: Build Solution
            script:
                - dotnet build
        - step: &Test-step
            name: Execute Tests
            script:
                - dotnet test

pipelines:
    default:
        - step: *Restore-step
        - step: *Build-step
        - step: *Test-step
    branches:
        master:
            - step: *Restore-step
            - step: *Build-step
            - step: *Test-step
            - step:
                name: Deploy Application
                script:
                    - cd MyPortfolio/
                    - sed -i -e "s/<PUT-YOUR-GOOGLE-MAPS-API-KEY-HERE>/$GOOGLE_MAPS_API_KEY/g" appsettings.json
                    - sed -i -e "s/<HOST>/$DATABASE_HOST/g" appsettings.json
                    - sed -i -e "s/<DATABASE>/$DATABASE_NAME/g" appsettings.json
                    - sed -i -e "s/<USERNAME>/$DATABASE_USERNAME/g" appsettings.json
                    - sed -i -e "s/<PASSWORD>/$DATABASE_PASSWORD/g" appsettings.json
                    - docker version
                    - docker build -t portfolioapp -f Dockerfile .
                    - docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
                    - docker tag portfolioapp registry.heroku.com/$HEROKU_APP_NAME/web
                    - docker push registry.heroku.com/$HEROKU_APP_NAME/web
                    - curl https://cli-assets.heroku.com/install.sh | sh
                    - heroku container:release web -a $HEROKU_APP_NAME
                services:
                    - docker
