image: microsoft/dotnet:2.2-sdk

pipelines:
  default:
    - step:
        caches:
            - dotnetcore
        name: 
            Restore Solution
        script: 
            - dotnet restore
    - step:
        name:
            Build Solution
        script:
            - dotnet build
    - step:
        name:
            Execute Tests
        script:
            - dotnet test
