image: microsoft/dotnet:2.2-sdk

definitions:
    steps:
        - step: &Restore-step
            name: Restore Solution
            script:
                - dotnet restore
        - step: &Build-step
            name: Build Solution
            script:
                - dotnet build
        - step: &Test-step
            name: Execute Tests
            script:
                - dotnet test

pipelines:
    default:
        - step: *Restore-step
        - step: *Build-step
        - step: *Test-step
    branches:
        master:
            - step: *Restore-step
            - step: *Build-step
            - step: *Test-step
            - step:
                name: Deploy Application
                script:
                    - docker version
                    - sed -i -e 's/<PUT-YOUR-GOOGLE-MAPS-API-KEY-HERE>/$GOOGLE_MAPS_API_KEY/g' ./MyPortfolio/appsettings.json
                    - sed -i -e 's/<HOST>/$DATABASE_HOST/g' ./MyPortfolio/appsettings.json
                    - sed -i -e 's/<DATABASE>/$DATABASE_NAME/g' ./MyPortfolio/appsettings.json
                    - sed -i -e 's/<USERNAME>/$DATABASE_USERNAME/g' ./MyPortfolio/appsettings.json
                    - sed -i -e 's/<PASSWORD>/$DATABASE_PASSWORD/g' ./MyPortfolio/appsettings.json
                    - cat ./MyPortfolio/appsettings.json
                services:
                    - docker
