image: microsoft/dotnet:2.2-sdk

definitions:
    steps:
        - step: &Restore-step
            name: Restore Solution
            script:
                - dotnet restore
        - step: &Build-step
            name: Build Solution
            script:
                - dotnet build
        - step: &Test-step
            name: Execute Tests
            script:
                - dotnet test

pipelines:
    default:
        - step: *Restore-step
        - step: *Build-step
        - step: *Test-step
    branches:
        master:
            - step: *Restore-step
            - step: *Build-step
            - step: *Test-step
            - step:
                name: Deploy Application
                script:
                    - echo "Deploying is only happening in master branch!"
                    - docker info
