steps:

# Replace the substitution variables
- name: bash
  env:
  - 'DATABASE_HOST=$_DATABASE_HOST'
  - 'DATABASE_NAME=$_DATABASE_NAME'
  - 'DATABASE_USERNAME=$_DATABASE_USERNAME'
  - 'DATABASE_PASSWORD=$_DATABASE_PASSWORD'
  - 'GOOGLE_MAPS_API_KEY=$_GOOGLE_MAPS_API_KEY'
  script: |
    #!/usr/bin/env bash
    echo "Start replacing substitution variables"
    cd MyPortfolio
    sed -i -e "s/<DB-HOST>/$DATABASE_HOST/g" appsettings.json
    sed -i -e "s/<DB-NAME>/$DATABASE_NAME/g" appsettings.json
    sed -i -e "s/<DB-USERNAME>/$DATABASE_USERNAME/g" appsettings.json
    sed -i -e "s/<DB-PASSWORD>/$DATABASE_PASSWORD/g" appsettings.json
    sed -i -e "s/<GOOGLE-MAPS-API-KEY>/$GOOGLE_MAPS_API_KEY/g" appsettings.json
    echo "Finished substitution variables replacements"

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/myportfolio:$COMMIT_SHA', './MyPortfolio/']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/myportfolio:$COMMIT_SHA']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'myportfolio'
  - '--image'
  - 'gcr.io/$PROJECT_ID/myportfolio:$COMMIT_SHA'
  - '--region'
  - '$_MYPORTFOLIO_REGION'
images:
- 'gcr.io/$PROJECT_ID/myportfolio:$COMMIT_SHA'