version: '3.8'

services:

  postgresqldb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - postgresqldb:/var/lib/postgresql/data
    networks:
      - common
      
volumes:
  postgresqldb:
    driver: local

networks:
  common:
    driver: bridge
