name: MyPortfolio Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-Library:

    runs-on: ubuntu-latest

    steps:
    - name: Installing dotnet core 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Verifying dotnet version
      run: dotnet --version

    - name: Location
      run: pwd

    - name: Files
      run: dir
      
    - name: Restoring MyPortfolio dependencies
      run: dotnet restore --no-cache

    - name: Building MyPortfolio Application
      run: dotnet build --no-restore

    - name: Restoring TestCoverage dependencies
      run: cd ../TestCoverage; dotnet restore --no-cache

    - name: Building TestCoverage Application
      run: cd ../TestCoverage; dotnet build --no-restore

    - name: Running TestCoverage Unit Tests
      run: cd ../TestCoverage; dotnet test